// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzvdlsxNowhaVvzex2A6PNJWUewgRmmfk',
    appId: '1:379558566186:web:af90358e19723a5e646653',
    messagingSenderId: '379558566186',
    projectId: 'gallery-2e7a0',
    authDomain: 'gallery-2e7a0.firebaseapp.com',
    storageBucket: 'gallery-2e7a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwJW0QqijPk5v7f0bNlQQ3DRQA2K48iac',
    appId: '1:379558566186:android:f79f4ad28b491320646653',
    messagingSenderId: '379558566186',
    projectId: 'gallery-2e7a0',
    storageBucket: 'gallery-2e7a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEUrOPr9NUVi_6rARyP9l8AW7-aQGf6os',
    appId: '1:379558566186:ios:d6364041164855f5646653',
    messagingSenderId: '379558566186',
    projectId: 'gallery-2e7a0',
    storageBucket: 'gallery-2e7a0.firebasestorage.app',
    iosBundleId: 'com.example.galleryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEUrOPr9NUVi_6rARyP9l8AW7-aQGf6os',
    appId: '1:379558566186:ios:d6364041164855f5646653',
    messagingSenderId: '379558566186',
    projectId: 'gallery-2e7a0',
    storageBucket: 'gallery-2e7a0.firebasestorage.app',
    iosBundleId: 'com.example.galleryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzvdlsxNowhaVvzex2A6PNJWUewgRmmfk',
    appId: '1:379558566186:web:2f8629d26cf2b0ce646653',
    messagingSenderId: '379558566186',
    projectId: 'gallery-2e7a0',
    authDomain: 'gallery-2e7a0.firebaseapp.com',
    storageBucket: 'gallery-2e7a0.firebasestorage.app',
  );
}
